# Generated by Django 3.0.4 on 2020-04-24 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(max_length=50, unique=True)),
                ('title', models.TextField(max_length=50)),
                ('date', models.TextField(blank=True, max_length=50)),
                ('guest_msg', models.TextField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('price', models.FloatField(editable=False)),
                ('img_url', models.TextField(max_length=100)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Memorial')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(editable=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('registry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.RegistryItem')),
            ],
        ),
    ]
