# Generated by Django 3.0.4 on 2020-04-24 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_itempayment_memorial_registryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(editable=False)),
                ('amount', models.FloatField(editable=False)),
                ('payee_email', models.EmailField(editable=False, max_length=70)),
                ('payment_id', models.TextField(editable=False, max_length=100)),
                ('card_id', models.TextField(editable=False, max_length=100)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Memorial')),
            ],
        ),
        migrations.AddField(
            model_name='registryitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ItemPayment',
        ),
    ]
